# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcomponent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.platformtemplate', verbose_name='\u6a21\u7248'),
        ),
    ]
