# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180321_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformcomponent',
            name='type',
        ),
        migrations.AddField(
            model_name='platformcomponent',
            name='status',
            field=models.CharField(default='up', max_length=5, verbose_name='\u72b6\u6001'),
        ),
    ]
